---
- id: shfmt
  name: shfmt
  description: Shell script formatter
  entry: hooks/shfmt
  language: script
  types: [shell]

- id: clang-tidy-nolint
  name: clang-tidy-nolint
  description: Formats clang-tidy NOLINT comments and removes unused ones
  entry: clang_tidy_nolint.py
  language: python
  files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
